#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT=$(cd "$SCRIPT_DIR/../../.." && pwd)

: "${COGNITO_USER_POOL_ID:?Missing COGNITO_USER_POOL_ID}"
: "${COGNITO_CLIENT_ID:?Missing COGNITO_CLIENT_ID}"
: "${S3_BUCKET_NAME:?Missing S3_BUCKET_NAME}"
: "${ODOO_OAUTH_PROVIDER_ID:?Missing ODOO_OAUTH_PROVIDER_ID}"
: "${ODOO_API_KEY:?Missing ODOO_API_KEY}"

ODOO_BASE_URL=${ODOO_BASE_URL:-https://erp.odootest.mvpstart.click}
ODOO_DB_NAME=${ODOO_DB_NAME:-devlyn_com}
ODOO_EVENT_INGEST_URL=${ODOO_EVENT_INGEST_URL:-http://127.0.0.1:8069/biometric/api/v1/event}
AUTH_BASE_URL=${AUTH_BASE_URL:-https://auth.odootest.mvpstart.click}
BIOMETRIC_MODE=${BIOMETRIC_MODE:-admin_demo_only}
BIOMETRIC_ADMIN_DEMO_LOGIN=${BIOMETRIC_ADMIN_DEMO_LOGIN:-admin}
MYSQL_FALLBACK_ENABLED=${MYSQL_FALLBACK_ENABLED:-false}
ATTENDANCE_SYNC_ENABLED=${ATTENDANCE_SYNC_ENABLED:-false}
GPS_REQUIRED=${GPS_REQUIRED:-true}
WEBAUTHN_ENABLED=${WEBAUTHN_ENABLED:-false}
WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID:-auth.odootest.mvpstart.click}
WEBAUTHN_RP_NAME=${WEBAUTHN_RP_NAME:-Odoo Biometric Auth}

cat > "$PROJECT_ROOT/server_config/auth_gateway/.env" <<ENV
APP_NAME=odoo-biometric-auth-gateway
APP_ENV=prod
APP_DEBUG=false
APP_SECRET_KEY=${APP_SECRET_KEY:-change-me-$(date +%s)}

AWS_REGION=us-east-1
COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}

REKOGNITION_LIVENESS_THRESHOLD=80
REKOGNITION_MAX_ATTEMPTS=3
LIVENESS_MOCK_MODE=${LIVENESS_MOCK_MODE:-false}

S3_BUCKET_NAME=${S3_BUCKET_NAME}
S3_PUBLIC_BASE_URL=${S3_PUBLIC_BASE_URL:-}

ODOO_BASE_URL=${ODOO_BASE_URL}
ODOO_DB_NAME=${ODOO_DB_NAME}
ODOO_OAUTH_PROVIDER_ID=${ODOO_OAUTH_PROVIDER_ID}
ODOO_EVENT_INGEST_URL=${ODOO_EVENT_INGEST_URL}
ODOO_API_KEY=${ODOO_API_KEY}

AUTH_BASE_URL=${AUTH_BASE_URL}
BIOMETRIC_MODE=${BIOMETRIC_MODE}
BIOMETRIC_ADMIN_DEMO_LOGIN=${BIOMETRIC_ADMIN_DEMO_LOGIN}
ATTENDANCE_SYNC_ENABLED=${ATTENDANCE_SYNC_ENABLED}

MYSQL_FALLBACK_ENABLED=${MYSQL_FALLBACK_ENABLED}
MYSQL_FALLBACK_CONNECTION_FILE=/opt/auth-gateway/connection_values.json

GPS_REQUIRED=${GPS_REQUIRED}
WEBAUTHN_ENABLED=${WEBAUTHN_ENABLED}
WEBAUTHN_RP_ID=${WEBAUTHN_RP_ID}
WEBAUTHN_RP_NAME=${WEBAUTHN_RP_NAME}
ENV

echo "Generated $PROJECT_ROOT/server_config/auth_gateway/.env"
