from odoo import models, fields

class ResUsers(models.Model):
    _inherit = 'res.users'

    property_name = fields.Char()
    property_lot = fields.Char()
    property_footage = fields.Char()
    property_amount = fields.Char()
    property_internal_code = fields.Char()
    condominium_name = fields.Char()
    monthly_payments_1_to_48 = fields.Char()
    monthly_payments_49_to_120 = fields.Char()
    monthly_payments_121_to_180 = fields.Char()
    monthly_payments_181_to_240 = fields.Char()
    amount_finance = fields.Float()
    hitch = fields.Float()
    hitch_text = fields.Char()
    finance_months = fields.Integer()
    total_sale_amount = fields.Float()
    monthly_payments_1_to_48_text = fields.Char()
    monthly_payments_49_to_120_text = fields.Char()
    monthly_payments_121_to_180_text = fields.Char()
    monthly_payments_181_to_240_text = fields.Char()
    loan_lines_text = fields.Text()
    vat_amount = fields.Float()
    vat_amount_text = fields.Char()
    total_without_tax = fields.Float()
    total_without_tax_text = fields.Char()
    maintenance_fee = fields.Float()
    maintenance_fee_text = fields.Char()
    property_pricing = fields.Float()
    property_pricing_text = fields.Char()
    related_public_deeds = fields.Char()
    recent_public_deed = fields.Char()
    otherwise_clause = fields.Char()
    compliance_clause = fields.Char()
    company_legal_name = fields.Char()
    company_legal_rep = fields.Char()
    company_constitutive_act = fields.Char()
    company_notary = fields.Char()
    company_address = fields.Char()
    company_email = fields.Char()
    partner_related_public_deeds = fields.Char()
    partner_recent_public_deed = fields.Char()
    partner_legal_name = fields.Char()
    partner_legal_representative = fields.Char()
    partner_constitutive_deed = fields.Char()
    partner_current_notary = fields.Char()
    partner_registered_address = fields.Char()
    partner_contact_email = fields.Char()

    person_type_client = fields.Char()
    full_name_client = fields.Char()
    curp_client = fields.Char()
    rfc_client = fields.Char()
    marital_status_client = fields.Char()
    nationality_client = fields.Char()
    address_client = fields.Text()
    phone_number_client = fields.Char()
    email_client = fields.Char()
    official_id_client = fields.Char()
    lives_in_house_client = fields.Char()
    studies_client = fields.Char()
    profession_client = fields.Char()
    occupation_client = fields.Char()
    employer_name_client = fields.Char()
    job_position_client = fields.Char()
    seniority_client = fields.Char()
    employer_phone_client = fields.Char()
    employer_address_client = fields.Text()
    place_of_birth_client = fields.Char()
    date_of_birth_client = fields.Date()
    applies_assets_client = fields.Char()
    first_names_client = fields.Char()
    last_name_materno_client = fields.Char()
    last_name_paterno_client = fields.Char()

    stockholder_full_name_1 = fields.Char()
    stockholder_address_1 = fields.Text()
    stockholder_lives_in_house_1 = fields.Boolean()
    stockholder_studies_1 = fields.Char()
    stockholder_profession_1 = fields.Char()
    stockholder_marital_status_1 = fields.Char()
    stockholder_phone_number_1 = fields.Char()
    stockholder_email_1 = fields.Char()
    stockholder_nationality_1 = fields.Char()
    stockholder_rfc_1 = fields.Char()
    stockholder_curp_1 = fields.Char()
    stockholder_occupation_1 = fields.Char()
    stockholder_job_position_1 = fields.Char()
    stockholder_seniority_1 = fields.Char()
    stockholder_employer_name_1 = fields.Char()
    stockholder_employer_phone_1 = fields.Char()
    stockholder_employer_address_1 = fields.Char()
    stockholder_applies_assets_1 = fields.Char()
    stockholder_shares_percentage_1 = fields.Char()

    stockholder_full_name_2 = fields.Char()
    stockholder_address_2 = fields.Text()
    stockholder_lives_in_house_2 = fields.Boolean()
    stockholder_studies_2 = fields.Char()
    stockholder_profession_2 = fields.Char()
    stockholder_marital_status_2 = fields.Char()
    stockholder_phone_number_2 = fields.Char()
    stockholder_email_2 = fields.Char()
    stockholder_nationality_2 = fields.Char()
    stockholder_rfc_2 = fields.Char()
    stockholder_curp_2 = fields.Char()
    stockholder_occupation_2 = fields.Char()
    stockholder_job_position_2 = fields.Char()
    stockholder_seniority_2 = fields.Char()
    stockholder_employer_name_2 = fields.Char()
    stockholder_employer_phone_2 = fields.Char()
    stockholder_employer_address_2 = fields.Char()
    stockholder_applies_assets_2 = fields.Char()
    stockholder_shares_percentage_2 = fields.Char()

    stockholder_full_name_3 = fields.Char()
    stockholder_address_3 = fields.Text()
    stockholder_lives_in_house_3 = fields.Boolean()
    stockholder_studies_3 = fields.Char()
    stockholder_profession_3 = fields.Char()
    stockholder_marital_status_3 = fields.Char()
    stockholder_phone_number_3 = fields.Char()
    stockholder_email_3 = fields.Char()
    stockholder_nationality_3 = fields.Char()
    stockholder_rfc_3 = fields.Char()
    stockholder_curp_3 = fields.Char()
    stockholder_occupation_3 = fields.Char()
    stockholder_job_position_3 = fields.Char()
    stockholder_seniority_3 = fields.Char()
    stockholder_employer_name_3 = fields.Char()
    stockholder_employer_phone_3 = fields.Char()
    stockholder_employer_address_3 = fields.Char()
    stockholder_applies_assets_3 = fields.Char()
    stockholder_shares_percentage_3 = fields.Char()

    stockholder_full_name_4 = fields.Char()
    stockholder_address_4 = fields.Text()
    stockholder_lives_in_house_4 = fields.Boolean()
    stockholder_studies_4 = fields.Char()
    stockholder_profession_4 = fields.Char()
    stockholder_marital_status_4 = fields.Char()
    stockholder_phone_number_4 = fields.Char()
    stockholder_email_4 = fields.Char()
    stockholder_nationality_4 = fields.Char()
    stockholder_rfc_4 = fields.Char()
    stockholder_curp_4 = fields.Char()
    stockholder_occupation_4 = fields.Char()
    stockholder_job_position_4 = fields.Char()
    stockholder_seniority_4 = fields.Char()
    stockholder_employer_name_4 = fields.Char()
    stockholder_employer_phone_4 = fields.Char()
    stockholder_employer_address_4 = fields.Char()
    stockholder_applies_assets_4 = fields.Char()
    stockholder_shares_percentage_4 = fields.Char()

    stockholder_full_name_5 = fields.Char()
    stockholder_address_5 = fields.Text()
    stockholder_lives_in_house_5 = fields.Boolean()
    stockholder_studies_5 = fields.Char()
    stockholder_profession_5 = fields.Char()
    stockholder_marital_status_5 = fields.Char()
    stockholder_phone_number_5 = fields.Char()
    stockholder_email_5 = fields.Char()
    stockholder_nationality_5 = fields.Char()
    stockholder_rfc_5 = fields.Char()
    stockholder_curp_5 = fields.Char()
    stockholder_occupation_5 = fields.Char()
    stockholder_job_position_5 = fields.Char()
    stockholder_seniority_5 = fields.Char()
    stockholder_employer_name_5 = fields.Char()
    stockholder_employer_phone_5 = fields.Char()
    stockholder_employer_address_5 = fields.Char()
    stockholder_applies_assets_5 = fields.Char()
    stockholder_shares_percentage_5 = fields.Char()

    stockholder_full_name_6 = fields.Char()
    stockholder_address_6 = fields.Text()
    stockholder_lives_in_house_6 = fields.Boolean()
    stockholder_studies_6 = fields.Char()
    stockholder_profession_6 = fields.Char()
    stockholder_marital_status_6 = fields.Char()
    stockholder_phone_number_6 = fields.Char()
    stockholder_email_6 = fields.Char()
    stockholder_nationality_6 = fields.Char()
    stockholder_rfc_6 = fields.Char()
    stockholder_curp_6 = fields.Char()
    stockholder_occupation_6 = fields.Char()
    stockholder_job_position_6 = fields.Char()
    stockholder_seniority_6 = fields.Char()
    stockholder_employer_name_6 = fields.Char()
    stockholder_employer_phone_6 = fields.Char()
    stockholder_employer_address_6 = fields.Char()
    stockholder_applies_assets_6 = fields.Char()
    stockholder_shares_percentage_6 = fields.Char()

    stockholder_full_name_7 = fields.Char()
    stockholder_address_7 = fields.Text()
    stockholder_lives_in_house_7 = fields.Boolean()
    stockholder_studies_7 = fields.Char()
    stockholder_profession_7 = fields.Char()
    stockholder_marital_status_7 = fields.Char()
    stockholder_phone_number_7 = fields.Char()
    stockholder_email_7 = fields.Char()
    stockholder_nationality_7 = fields.Char()
    stockholder_rfc_7 = fields.Char()
    stockholder_curp_7 = fields.Char()
    stockholder_occupation_7 = fields.Char()
    stockholder_job_position_7 = fields.Char()
    stockholder_seniority_7 = fields.Char()
    stockholder_employer_name_7 = fields.Char()
    stockholder_employer_phone_7 = fields.Char()
    stockholder_employer_address_7 = fields.Char()
    stockholder_applies_assets_7 = fields.Char()
    stockholder_shares_percentage_7 = fields.Char()

    stockholder_full_name_8 = fields.Char()
    stockholder_address_8 = fields.Text()
    stockholder_lives_in_house_8 = fields.Boolean()
    stockholder_studies_8 = fields.Char()
    stockholder_profession_8 = fields.Char()
    stockholder_marital_status_8 = fields.Char()
    stockholder_phone_number_8 = fields.Char()
    stockholder_email_8 = fields.Char()
    stockholder_nationality_8 = fields.Char()
    stockholder_rfc_8 = fields.Char()
    stockholder_curp_8 = fields.Char()
    stockholder_occupation_8 = fields.Char()
    stockholder_job_position_8 = fields.Char()
    stockholder_seniority_8 = fields.Char()
    stockholder_employer_name_8 = fields.Char()
    stockholder_employer_phone_8 = fields.Char()
    stockholder_employer_address_8 = fields.Char()
    stockholder_applies_assets_8 = fields.Char()
    stockholder_shares_percentage_8 = fields.Char()

    stockholder_full_name_9 = fields.Char()
    stockholder_address_9 = fields.Text()
    stockholder_lives_in_house_9 = fields.Boolean()
    stockholder_studies_9 = fields.Char()
    stockholder_profession_9 = fields.Char()
    stockholder_marital_status_9 = fields.Char()
    stockholder_phone_number_9 = fields.Char()
    stockholder_email_9 = fields.Char()
    stockholder_nationality_9 = fields.Char()
    stockholder_rfc_9 = fields.Char()
    stockholder_curp_9 = fields.Char()
    stockholder_occupation_9 = fields.Char()
    stockholder_job_position_9 = fields.Char()
    stockholder_seniority_9 = fields.Char()
    stockholder_employer_name_9 = fields.Char()
    stockholder_employer_phone_9 = fields.Char()
    stockholder_employer_address_9 = fields.Char()
    stockholder_applies_assets_9 = fields.Char()
    stockholder_shares_percentage_9 = fields.Char()

    stockholder_full_name_10 = fields.Char()
    stockholder_address_10 = fields.Text()
    stockholder_lives_in_house_10 = fields.Boolean()
    stockholder_studies_10 = fields.Char()
    stockholder_profession_10 = fields.Char()
    stockholder_marital_status_10 = fields.Char()
    stockholder_phone_number_10 = fields.Char()
    stockholder_email_10 = fields.Char()
    stockholder_nationality_10 = fields.Char()
    stockholder_rfc_10 = fields.Char()
    stockholder_curp_10 = fields.Char()
    stockholder_occupation_10 = fields.Char()
    stockholder_job_position_10 = fields.Char()
    stockholder_seniority_10 = fields.Char()
    stockholder_employer_name_10 = fields.Char()
    stockholder_employer_phone_10 = fields.Char()
    stockholder_employer_address_10 = fields.Char()
    stockholder_applies_assets_10 = fields.Char()
    stockholder_shares_percentage_10 = fields.Char()

    street_name_1 = fields.Char(string='Street 1')
    external_number_1 = fields.Char(string='Exterior Number 1')
    number_1 = fields.Char(string='Number 1')
    internal_number_1 = fields.Char(string='Interior Number 1')
    suburb_1 = fields.Char(string='Neighborhood / Suburb 1')
    municipality_1 = fields.Char(string='Municipality / City 1')
    state_name_1 = fields.Char(string='State 1')
    zip_code_1 = fields.Char(string='ZIP Code 1')

    street_name_2 = fields.Char(string='Street 2')
    external_number_2 = fields.Char(string='Exterior Number 2')
    number_2 = fields.Char(string='Number 2')
    internal_number_2 = fields.Char(string='Interior Number 2')
    suburb_2 = fields.Char(string='Neighborhood / Suburb 2')
    municipality_2 = fields.Char(string='Municipality / City 2')
    state_name_2 = fields.Char(string='State 2')
    zip_code_2 = fields.Char(string='ZIP Code 2')

    street_name_3 = fields.Char(string='Street 3')
    external_number_3 = fields.Char(string='Exterior Number 3')
    number_3 = fields.Char(string='Number 3')
    internal_number_3 = fields.Char(string='Interior Number 3')
    suburb_3 = fields.Char(string='Neighborhood / Suburb 3')
    municipality_3 = fields.Char(string='Municipality / City 3')
    state_name_3 = fields.Char(string='State 3')
    zip_code_3 = fields.Char(string='ZIP Code 3')

    street_name_4 = fields.Char(string='Street 4')
    external_number_4 = fields.Char(string='Exterior Number 4')
    number_4 = fields.Char(string='Number 4')
    internal_number_4 = fields.Char(string='Interior Number 4')
    suburb_4 = fields.Char(string='Neighborhood / Suburb 4')
    municipality_4 = fields.Char(string='Municipality / City 4')
    state_name_4 = fields.Char(string='State 4')
    zip_code_4 = fields.Char(string='ZIP Code 4')

    street_name_5 = fields.Char(string='Street 5')
    external_number_5 = fields.Char(string='Exterior Number 5')
    number_5 = fields.Char(string='Number 5')
    internal_number_5 = fields.Char(string='Interior Number 5')
    suburb_5 = fields.Char(string='Neighborhood / Suburb 5')
    municipality_5 = fields.Char(string='Municipality / City 5')
    state_name_5 = fields.Char(string='State 5')
    zip_code_5 = fields.Char(string='ZIP Code 5')

    street_name_6 = fields.Char(string='Street 6')
    external_number_6 = fields.Char(string='Exterior Number 6')
    number_6 = fields.Char(string='Number 6')
    internal_number_6 = fields.Char(string='Interior Number 6')
    suburb_6 = fields.Char(string='Neighborhood / Suburb 6')
    municipality_6 = fields.Char(string='Municipality / City 6')
    state_name_6 = fields.Char(string='State 6')
    zip_code_6 = fields.Char(string='ZIP Code 6')

    street_name_7 = fields.Char(string='Street 7')
    external_number_7 = fields.Char(string='Exterior Number 7')
    number_7 = fields.Char(string='Number 7')
    internal_number_7 = fields.Char(string='Interior Number 7')
    suburb_7 = fields.Char(string='Neighborhood / Suburb 7')
    municipality_7 = fields.Char(string='Municipality / City 7')
    state_name_7 = fields.Char(string='State 7')
    zip_code_7 = fields.Char(string='ZIP Code 7')

    street_name_8 = fields.Char(string='Street 8')
    external_number_8 = fields.Char(string='Exterior Number 8')
    number_8 = fields.Char(string='Number 8')
    internal_number_8 = fields.Char(string='Interior Number 8')
    suburb_8 = fields.Char(string='Neighborhood / Suburb 8')
    municipality_8 = fields.Char(string='Municipality / City 8')
    state_name_8 = fields.Char(string='State 8')
    zip_code_8 = fields.Char(string='ZIP Code 8')

    street_name_9 = fields.Char(string='Street 9')
    external_number_9 = fields.Char(string='Exterior Number 9')
    number_9 = fields.Char(string='Number 9')
    internal_number_9 = fields.Char(string='Interior Number 9')
    suburb_9 = fields.Char(string='Neighborhood / Suburb 9')
    municipality_9 = fields.Char(string='Municipality / City 9')
    state_name_9 = fields.Char(string='State 9')
    zip_code_9 = fields.Char(string='ZIP Code 9')

    street_name_10 = fields.Char(string='Street 10')
    external_number_10 = fields.Char(string='Exterior Number 10')
    number_10 = fields.Char(string='Number 10')
    internal_number_10 = fields.Char(string='Interior Number 10')
    suburb_10 = fields.Char(string='Neighborhood / Suburb 10')
    municipality_10 = fields.Char(string='Municipality / City 10')
    state_name_10 = fields.Char(string='State 10')
    zip_code_10 = fields.Char(string='ZIP Code 10')

    full_name_2 = fields.Char()
    full_name_file_2 = fields.Binary()
    full_name_file_name_2 = fields.Char()
    official_id_2 = fields.Char()
    official_id_file_2 = fields.Binary()
    official_id_file_name_2 = fields.Char()
    address_2 = fields.Text()
    street_name_2 = fields.Char()
    external_number_2 = fields.Char()
    number_2 = fields.Char()
    internal_number_2 = fields.Char()
    suburb_2 = fields.Char()
    municipality_2 = fields.Char()
    state_name_2 = fields.Char()
    zip_code_2 = fields.Char()
    address_file_2 = fields.Binary()
    address_file_name_2 = fields.Char()
    lives_in_house_2 = fields.Boolean()
    studies_2 = fields.Char()
    profession_2 = fields.Char()
    marital_status_2 = fields.Char()
    phone_number_2 = fields.Char()
    email_2 = fields.Char()
    nationality_2 = fields.Char()
    rfc_2 = fields.Char()
    rfc_file_2 = fields.Binary()
    rfc_file_name_2 = fields.Char()
    curp_2 = fields.Char()
    curp_file_2 = fields.Binary()
    curp_file_name_2 = fields.Char()
    occupation_2 = fields.Char()
    job_position_2 = fields.Char()
    seniority_2 = fields.Char()
    employer_name_2 = fields.Char()
    employer_phone_2 = fields.Char()
    employer_address_2 = fields.Char()
    place_of_birth_2 = fields.Char()
    date_of_birth_2 = fields.Date()
    applies_assets_2 = fields.Char()

    full_name_3 = fields.Char()
    full_name_file_3 = fields.Binary()
    full_name_file_name_3 = fields.Char()
    official_id_3 = fields.Char()
    official_id_file_3 = fields.Binary()
    official_id_file_name_3 = fields.Char()
    address_3 = fields.Text()
    street_name_3 = fields.Char()
    external_number_3 = fields.Char()
    number_3 = fields.Char()
    internal_number_3 = fields.Char()
    suburb_3 = fields.Char()
    municipality_3 = fields.Char()
    state_name_3 = fields.Char()
    zip_code_3 = fields.Char()
    address_file_3 = fields.Binary()
    address_file_name_3 = fields.Char()
    lives_in_house_3 = fields.Boolean()
    studies_3 = fields.Char()
    profession_3 = fields.Char()
    marital_status_3 = fields.Char()
    phone_number_3 = fields.Char()
    email_3 = fields.Char()
    nationality_3 = fields.Char()
    rfc_3 = fields.Char()
    rfc_file_3 = fields.Binary()
    rfc_file_name_3 = fields.Char()
    curp_3 = fields.Char()
    curp_file_3 = fields.Binary()
    curp_file_name_3 = fields.Char()
    occupation_3 = fields.Char()
    job_position_3 = fields.Char()
    seniority_3 = fields.Char()
    employer_name_3 = fields.Char()
    employer_phone_3 = fields.Char()
    employer_address_3 = fields.Char()
    place_of_birth_3 = fields.Char()
    date_of_birth_3 = fields.Date()
    applies_assets_3 = fields.Char()

    full_name_4 = fields.Char()
    full_name_file_4 = fields.Binary()
    full_name_file_name_4 = fields.Char()
    official_id_4 = fields.Char()
    official_id_file_4 = fields.Binary()
    official_id_file_name_4 = fields.Char()
    address_4 = fields.Text()
    street_name_4 = fields.Char()
    external_number_4 = fields.Char()
    number_4 = fields.Char()
    internal_number_4 = fields.Char()
    suburb_4 = fields.Char()
    municipality_4 = fields.Char()
    state_name_4 = fields.Char()
    zip_code_4 = fields.Char()
    address_file_4 = fields.Binary()
    address_file_name_4 = fields.Char()
    lives_in_house_4 = fields.Boolean()
    studies_4 = fields.Char()
    profession_4 = fields.Char()
    marital_status_4 = fields.Char()
    phone_number_4 = fields.Char()
    email_4 = fields.Char()
    nationality_4 = fields.Char()
    rfc_4 = fields.Char()
    rfc_file_4 = fields.Binary()
    rfc_file_name_4 = fields.Char()
    curp_4 = fields.Char()
    curp_file_4 = fields.Binary()
    curp_file_name_4 = fields.Char()
    occupation_4 = fields.Char()
    job_position_4 = fields.Char()
    seniority_4 = fields.Char()
    employer_name_4 = fields.Char()
    employer_phone_4 = fields.Char()
    employer_address_4 = fields.Char()
    place_of_birth_4 = fields.Char()
    date_of_birth_4 = fields.Date()
    applies_assets_4 = fields.Char()

    full_name_5 = fields.Char()
    full_name_file_5 = fields.Binary()
    full_name_file_name_5 = fields.Char()
    official_id_5 = fields.Char()
    official_id_file_5 = fields.Binary()
    official_id_file_name_5 = fields.Char()
    address_5 = fields.Text()
    street_name_5 = fields.Char()
    external_number_5 = fields.Char()
    number_5 = fields.Char()
    internal_number_5 = fields.Char()
    suburb_5 = fields.Char()
    municipality_5 = fields.Char()
    state_name_5 = fields.Char()
    zip_code_5 = fields.Char()
    address_file_5 = fields.Binary()
    address_file_name_5 = fields.Char()
    lives_in_house_5 = fields.Boolean()
    studies_5 = fields.Char()
    profession_5 = fields.Char()
    marital_status_5 = fields.Char()
    phone_number_5 = fields.Char()
    email_5 = fields.Char()
    nationality_5 = fields.Char()
    rfc_5 = fields.Char()
    rfc_file_5 = fields.Binary()
    rfc_file_name_5 = fields.Char()
    curp_5 = fields.Char()
    curp_file_5 = fields.Binary()
    curp_file_name_5 = fields.Char()
    occupation_5 = fields.Char()
    job_position_5 = fields.Char()
    seniority_5 = fields.Char()
    employer_name_5 = fields.Char()
    employer_phone_5 = fields.Char()
    employer_address_5 = fields.Char()
    place_of_birth_5 = fields.Char()
    date_of_birth_5 = fields.Date()
    applies_assets_5 = fields.Char()

    full_name_6 = fields.Char()
    full_name_file_6 = fields.Binary()
    full_name_file_name_6 = fields.Char()
    official_id_6 = fields.Char()
    official_id_file_6 = fields.Binary()
    official_id_file_name_6 = fields.Char()
    address_6 = fields.Text()
    street_name_6 = fields.Char()
    external_number_6 = fields.Char()
    number_6 = fields.Char()
    internal_number_6 = fields.Char()
    suburb_6 = fields.Char()
    municipality_6 = fields.Char()
    state_name_6 = fields.Char()
    zip_code_6 = fields.Char()
    address_file_6 = fields.Binary()
    address_file_name_6 = fields.Char()
    lives_in_house_6 = fields.Boolean()
    studies_6 = fields.Char()
    profession_6 = fields.Char()
    marital_status_6 = fields.Char()
    phone_number_6 = fields.Char()
    email_6 = fields.Char()
    nationality_6 = fields.Char()
    rfc_6 = fields.Char()
    rfc_file_6 = fields.Binary()
    rfc_file_name_6 = fields.Char()
    curp_6 = fields.Char()
    curp_file_6 = fields.Binary()
    curp_file_name_6 = fields.Char()
    occupation_6 = fields.Char()
    job_position_6 = fields.Char()
    seniority_6 = fields.Char()
    employer_name_6 = fields.Char()
    employer_phone_6 = fields.Char()
    employer_address_6 = fields.Char()
    place_of_birth_6 = fields.Char()
    date_of_birth_6 = fields.Date()
    applies_assets_6 = fields.Char()

    full_name_7 = fields.Char()
    full_name_file_7 = fields.Binary()
    full_name_file_name_7 = fields.Char()
    official_id_7 = fields.Char()
    official_id_file_7 = fields.Binary()
    official_id_file_name_7 = fields.Char()
    address_7 = fields.Text()
    street_name_7 = fields.Char()
    external_number_7 = fields.Char()
    number_7 = fields.Char()
    internal_number_7 = fields.Char()
    suburb_7 = fields.Char()
    municipality_7 = fields.Char()
    state_name_7 = fields.Char()
    zip_code_7 = fields.Char()
    address_file_7 = fields.Binary()
    address_file_name_7 = fields.Char()
    lives_in_house_7 = fields.Boolean()
    studies_7 = fields.Char()
    profession_7 = fields.Char()
    marital_status_7 = fields.Char()
    phone_number_7 = fields.Char()
    email_7 = fields.Char()
    nationality_7 = fields.Char()
    rfc_7 = fields.Char()
    rfc_file_7 = fields.Binary()
    rfc_file_name_7 = fields.Char()
    curp_7 = fields.Char()
    curp_file_7 = fields.Binary()
    curp_file_name_7 = fields.Char()
    occupation_7 = fields.Char()
    job_position_7 = fields.Char()
    seniority_7 = fields.Char()
    employer_name_7 = fields.Char()
    employer_phone_7 = fields.Char()
    employer_address_7 = fields.Char()
    place_of_birth_7 = fields.Char()
    date_of_birth_7 = fields.Date()
    applies_assets_7 = fields.Char()

    full_name_8 = fields.Char()
    full_name_file_8 = fields.Binary()
    full_name_file_name_8 = fields.Char()
    official_id_8 = fields.Char()
    official_id_file_8 = fields.Binary()
    official_id_file_name_8 = fields.Char()
    address_8 = fields.Text()
    street_name_8 = fields.Char()
    external_number_8 = fields.Char()
    number_8 = fields.Char()
    internal_number_8 = fields.Char()
    suburb_8 = fields.Char()
    municipality_8 = fields.Char()
    state_name_8 = fields.Char()
    zip_code_8 = fields.Char()
    address_file_8 = fields.Binary()
    address_file_name_8 = fields.Char()
    lives_in_house_8 = fields.Boolean()
    studies_8 = fields.Char()
    profession_8 = fields.Char()
    marital_status_8 = fields.Char()
    phone_number_8 = fields.Char()
    email_8 = fields.Char()
    nationality_8 = fields.Char()
    rfc_8 = fields.Char()
    rfc_file_8 = fields.Binary()
    rfc_file_name_8 = fields.Char()
    curp_8 = fields.Char()
    curp_file_8 = fields.Binary()
    curp_file_name_8 = fields.Char()
    occupation_8 = fields.Char()
    job_position_8 = fields.Char()
    seniority_8 = fields.Char()
    employer_name_8 = fields.Char()
    employer_phone_8 = fields.Char()
    employer_address_8 = fields.Char()
    place_of_birth_8 = fields.Char()
    date_of_birth_8 = fields.Date()
    applies_assets_8 = fields.Char()

    full_name_9 = fields.Char()
    full_name_file_9 = fields.Binary()
    full_name_file_name_9 = fields.Char()
    official_id_9 = fields.Char()
    official_id_file_9 = fields.Binary()
    official_id_file_name_9 = fields.Char()
    address_9 = fields.Text()
    street_name_9 = fields.Char()
    external_number_9 = fields.Char()
    number_9 = fields.Char()
    internal_number_9 = fields.Char()
    suburb_9 = fields.Char()
    municipality_9 = fields.Char()
    state_name_9 = fields.Char()
    zip_code_9 = fields.Char()
    address_file_9 = fields.Binary()
    address_file_name_9 = fields.Char()
    lives_in_house_9 = fields.Boolean()
    studies_9 = fields.Char()
    profession_9 = fields.Char()
    marital_status_9 = fields.Char()
    phone_number_9 = fields.Char()
    email_9 = fields.Char()
    nationality_9 = fields.Char()
    rfc_9 = fields.Char()
    rfc_file_9 = fields.Binary()
    rfc_file_name_9 = fields.Char()
    curp_9 = fields.Char()
    curp_file_9 = fields.Binary()
    curp_file_name_9 = fields.Char()
    occupation_9 = fields.Char()
    job_position_9 = fields.Char()
    seniority_9 = fields.Char()
    employer_name_9 = fields.Char()
    employer_phone_9 = fields.Char()
    employer_address_9 = fields.Char()
    place_of_birth_9 = fields.Char()
    date_of_birth_9 = fields.Date()
    applies_assets_9 = fields.Boolean()

    full_name_10 = fields.Char()
    full_name_file_10 = fields.Binary()
    full_name_file_name_10 = fields.Char()
    official_id_10 = fields.Char()
    official_id_file_10 = fields.Binary()
    official_id_file_name_10 = fields.Char()
    address_10 = fields.Text()
    street_name_10 = fields.Char()
    external_number_10 = fields.Char()
    number_10 = fields.Char()
    internal_number_10 = fields.Char()
    suburb_10 = fields.Char()
    municipality_10 = fields.Char()
    state_name_10 = fields.Char()
    zip_code_10 = fields.Char()
    address_file_10 = fields.Binary()
    address_file_name_10 = fields.Char()
    lives_in_house_10 = fields.Boolean()
    studies_10 = fields.Char()
    profession_10 = fields.Char()
    marital_status_10 = fields.Char()
    phone_number_10 = fields.Char()
    email_10 = fields.Char()
    nationality_10 = fields.Char()
    rfc_10 = fields.Char()
    rfc_file_10 = fields.Binary()
    rfc_file_name_10 = fields.Char()
    curp_10 = fields.Char()
    curp_file_10 = fields.Binary()
    curp_file_name_10 = fields.Char()
    occupation_10 = fields.Char()
    job_position_10 = fields.Char()
    seniority_10 = fields.Char()
    employer_name_10 = fields.Char()
    employer_phone_10 = fields.Char()
    employer_address_10 = fields.Char()
    place_of_birth_10 = fields.Char()
    date_of_birth_10 = fields.Date()
    applies_assets_10 = fields.Boolean()




