from . import property_contract_inherit
from . import loan_line
from . import installment_template_inherit
from . import finance_modality_lines
from . import sale_order
from . import crm_lead
from . import payment_terms
from . import difer_hitch
from . import property_reservation
from . import promotions_property
from . import product_template
from . import account_payment