server {
    listen 80;
    server_name mcp.odootest.mvpstart.click;

    access_log /var/log/nginx/odoo_mcp_http_access.log;
    error_log /var/log/nginx/odoo_mcp_http_error.log warn;

    root /var/www/html;

    location /.well-known/acme-challenge/ {
        allow all;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
